#!/bin/bash
SHOW=$1
if [ "${SHOW}" = "show" ]; then
	awk '{ print $3 - $2 "\t" $0 }' | sort -k1n,1  
else
	#awk '{ print $3 - $2 "\t" $0 }' | sort -k1n,1 | awk '{ $1 = ""; print $0 }' 
	awk '{ print $3 - $2 "\t" $0 }' | sort -k1n,1 | drop_first_col

fi
