#!/bin/sh

RUN=$1
CONTIG=$2
if [ "${CONTIG}" = "every" ] 
then
	#rm -rf /home/share/cnv/pipeline/results/all/working.${RUN}/coverage.track
	for line in `cat ${SVN_BASE}/cnv/chrom_list`
	do
		CONTIG=chr${line}
		echo Doing ${CONTIG}...
		$0 $RUN ${CONTIG}
		#cat /home/share/cnv/pipeline/results/${CONTIG}/working.${RUN}/coverage.track >> /home/share/cnv/pipeline/results/all/working.${RUN}/coverage.track
	done
else

	OUTDIR=${SVN_BASE}/cnv/results/${CONTIG}/working.${RUN}

	cat /home/share/cnv/pipeline/mask_regions/${CONTIG}.mask_regions /home/share/cnv/pipeline/contigbreaks/${CONTIG}.contigbreaks | sort -k1,1 -k2n,2 | intJoin > ${OUTDIR}/breaks
	echo "track name=covBreaks."${CONTIG} " visibility=dense " > $OUTDIR/coverage.track
	cat ${OUTDIR}/breaks >> ${OUTDIR}/coverage.track

	cat ${SVN_BASE}/cnv/datasets/kidd_loss_${CONTIG} ${SVN_BASE}/cnv/datasets/kidd_gain_${CONTIG} ${SVN_BASE}/cnv/results/${CONTIG}/working.${RUN}/${CONTIG}.cnvs | sort -k1,1 -k2n,2 | intJoin | sbsJoin2 | awk '{print $1, $2, $3, int(($3-$2) / 100) + 1; if ($6 == "") { print $1, $3+1, $3 + 10000, 100} else if (($5 - $3) < 20010) {print $1, $3+1, $5 -1 , 100} else { print $1, $3 + 1, $3 + 10000, 100; print $4, $5 - 10000, $5 - 1, 100}  }'  | sbsJoin2 | awk '{ print $1,$2,$3,$4; if (($1==$5) && ($6!="") && (($6 - $3) > 1)) print $1,$3 + 1 ,$6 - 1, 9000000; }' > ${OUTDIR}/coverageRegions
	
	
	echo >> ${OUTDIR}/coverage.track
	echo "track type=wiggle_0 name=solCoverage."${CONTIG} "visibility=full graphType=points" >> $OUTDIR/coverage.track
	cat $OUTDIR/coverageRegions | awk '{ if ($4 < 100) $4 = 100; print $0 }' | coverageTrack /data/cnv/coverage_maps/solexa/${CONTIG}.coverage ${OUTDIR}/breaks | awk '{ print $1"\t"$2"\t"$3+1"\t"$4 }' >> ${OUTDIR}/coverage.track

fi
